/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef} from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
 var x = useGLTF(props.data["add"])
  const { nodes, materials } = x


  return (
    <group ref={group} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.1, 0.03, 0.15]}>

        {
          props["data"]["gemo"].map((item,index)=>{
           
            var temGemo = nodes[item]["geometry"];
            var temMat = materials[props.data['material'][index]]
            // console.log(item,"**",nodes[item])
            return(
              <mesh geometry={temGemo} material={temMat} />
            )
          })
        
        }
       
      </group>
    </group>
  )
}

